const WEIXIN_LOGIN="WEIXIN_LOGIN";
const WEIXIN_SET_TOKEN = "WEIXIN_SET_TOKEN";

const WX_UP_SHARE="WX_UP_SHARE";

const ALL_PAGE_DATA="ALL_PAGE_DATA";


export default {
	WEIXIN_LOGIN,
	WEIXIN_SET_TOKEN,
	WX_UP_SHARE,
	ALL_PAGE_DATA
}