const WEIXIN_LOGIN="WEIXIN_LOGIN";

const ADMIN_LOGIN="ADMIN_LOGIN";
const ADMIN_REMOVE="ADMIN_REMOVE";
const ADMIN_LIST="ADMIN_LIST";


export default {
	WEIXIN_LOGIN,
	ADMIN_LOGIN,
	ADMIN_REMOVE,
	ADMIN_LIST
}